name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: hojang/easyshift-backend
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine target branch
        id: branch
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TARGET_BRANCH="${{ github.base_ref }}"
          else
            TARGET_BRANCH="${GITHUB_REF#refs/heads/}"
          fi
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          if [ "$TARGET_BRANCH" = "main" ]; then
            echo "Building production image..."
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --cache-from=type=registry,ref=${IMAGE_NAME}:cache \
              --cache-to=type=registry,ref=${IMAGE_NAME}:cache,mode=max \
              -f Dockerfile \
              -t ${IMAGE_NAME}:prod_${IMAGE_TAG} \
              -t ${IMAGE_NAME}:latest \
              --push .
          elif [ "$TARGET_BRANCH" = "develop" ]; then
            echo "Building development image..."
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --cache-from=type=registry,ref=${IMAGE_NAME}:cache \
              --cache-to=type=registry,ref=${IMAGE_NAME}:cache,mode=max \
              -f Dockerfile \
              -t ${IMAGE_NAME}:dev_${IMAGE_TAG} \
              --push .
          else
            echo "Unsupported branch: $TARGET_BRANCH"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    env:
      IMAGE_NAME: hojang/easyshift-backend
    strategy:
      matrix:
        include:
          - branch: main
            container: easyshift_prod
            port: 81
            db_url: ${{ secrets.DB_URL }}
            jwt_issuer: ${{ secrets.JWT_ISSUER }}
            jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
            client_id: ${{ secrets.KAKAO_CLIENT_ID }}
            client_secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
            redirect_uri: ${{ secrets.KAKAO_REDIRECT_URI }}
            authorization_uri: ${{ secrets.KAKAO_AUTHORIZATION_URI }}
            token_uri: ${{ secrets.KAKAO_TOKEN_URI }}
            user_info_uri: ${{ secrets.KAKAO_USER_INFO_URI }}
            scope: ${{ secrets.KAKAO_SCOPE }}
          - branch: develop
            container: easyshift_dev
            port: 8081
            db_url: ${{ secrets.DB_URL_DEVELOP }}
            jwt_issuer: ${{ secrets.JWT_ISSUER }}
            jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
            client_id: ${{ secrets.KAKAO_CLIENT_ID }}
            client_secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
            redirect_uri: ${{ secrets.KAKAO_REDIRECT_URI }}
            authorization_uri: ${{ secrets.KAKAO_AUTHORIZATION_URI }}
            token_uri: ${{ secrets.KAKAO_TOKEN_URI }}
            user_info_uri: ${{ secrets.KAKAO_USER_INFO_URI }}
            scope: ${{ secrets.KAKAO_SCOPE }}

    steps:
      - name: Deploy via SSH
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Pulling latest image: ${{ env.IMAGE_NAME }}"
            docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
            
            echo "Stopping and removing existing container"
            docker stop ${{ matrix.container }} || true
            docker rm ${{ matrix.container }} || true
            
            echo "Starting new container..."
            docker run -d --restart unless-stopped \
              --name ${{ matrix.container }} \
              -p 127.0.0.1:${{ matrix.port }}:${{ secrets.SERVER_PORT }} \
              --add-host=host.docker.internal:host-gateway \
              -e SERVER_PORT="${{ secrets.SERVER_PORT }}" \
              -e DB_URL="${{ matrix.db_url }}" \
              -e DB_DRIVER="${{ secrets.DB_DRIVER }}" \
              -e DB_DIALECT="${{ secrets.DB_DIALECT }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e JWT_ISSUER="${{ matrix.jwt_issuer }}" \
              -e JWT_SECRET_KEY="${{ matrix.jwt_secret_key }}" \
              -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID="${{ matrix.client_id }}" \
              -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET="${{ matrix.client_secret }}" \
              -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI="${{ matrix.redirect_uri }}" \
              -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_AUTHORIZATION_GRANT_TYPE="authorization_code" \
              -e SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_AUTHORIZATION_URI="${{ matrix.authorization_uri }}" \
              -e SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_TOKEN_URI="${{ matrix.token_uri }}" \
              -e SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_INFO_URI="${{ matrix.user_info_uri }}" \
              -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_SCOPE="${{ matrix.scope }}" \
              ${{ env.IMAGE_NAME }}:${{ github.sha }}